### ISSUE TITLE
Failing Ecosystem Modules List

### ISSUE THREAD

**Issue by samcv** [perl6/ecosystem#318] opened 2017-04-18 11:42 UTC
Hopefully this can be a group effort to try and get these failing packages passing. Feel free to add issues and link them here. If you aren't a collaborator with the repo, just reply and somebody else can add it to this main list :-) Thank you all!

# Failing
Log links are to specific lines in a Travis CI build that attempts to install all modules. This list is incomplete because this takes a very long time to do.
See here for full log:
**UPDATE**
I have a new format for the tests I am running on hack.p6c.org
There is a json file that's named for the date/time the test starts, and then a folder which contains log files for each module's installation. The JSON shows the exitcode, status and 'ok' or 'nok'. If the test times out there were be something indicating it there as well.

http://hack.p6c.org/~samcv/ecosystem-tests/

#### XXX
- at least 3 PR's fixing it dating from 2 years ago… https://github.com/ingydotnet/xxx-pm6/pulls
- NO LICENSE on project page.
- Should this be removed from the ecosystem? Been failing for 2 years and may not be re-releasable.
- Log
```
Undeclared routine:
    eval_lives_ok used at line 5. Did you mean 'eval-lives-ok', 'eval-dies-ok'?

t/ok.t .. No subtests run
```
- [ ] Reported
- [ ] Fixed

#### Data::Pretty:ver('0.0.2'):auth('github:masak')
- [ ] Reported
- [ ] Fixed
```
Could not find MONKEY_TYPING at line 1 in:
    /home/samcv/.zef/store/data-pretty.git/c5b3922c37e3b97c9f0910e2ad5e468e9463e894/lib
```

#### List::Utils
- [X] Reported https://github.com/colomon/List-Utils/issues/6
- [ ] Fixed

#### Text::Diff
- [Log](https://travis-ci.org/samcv/rakudo-appimage/jobs/223092218#L1962)
- [X] Reported https://github.com/Takadonet/Text--Diff/issues/8 April 17th 2017
- [ ] Fixed

#### IO::Prompter
- [Log](https://travis-ci.org/samcv/rakudo-appimage/jobs/223092218#L1408)
- [X] Reported MERGED https://github.com/colomon/io-prompter/pull/6
- [ ] Fixed partial
- Repo: https://github.com/colomon/io-prompter
- NO ISSUES TAB

#### [String::CRC32:ver('0.04'):auth('Cosimo Streppone')](https://github.com/cosimo/perl6-string-crc32)
- [Log](https://travis-ci.org/samcv/rakudo-appimage/jobs/223092220#L4201)
- [ ] Reported
- [ ] Fixed

#### Pod::Strip:ver('0.0.1'):auth('Jorn van Engelen')
- [ ] Reported
- [ ] Fixed
```
An exception occurred while evaluating a BEGIN
at /home/samcv/.zef/store/perl6-pod-strip.git/2bb9b9dc3d593cbddc53092dcc3519b2a666afeb/t/test.t:2
Exception details:
  Dynamic variable @*INC not found
    in block  at t/test.t line 2
```

#### Pluggable:ver('0.1.0'):auth('github:tony-o')
- [ ] Reported
- [ ] Fixed
```
Dynamic variable @*INC not found
  in method plugins at /home/sena/.zef/store/perl6-pluggable.git/2cb08cb57ed133e11577442d3ab0c4da63e593eb/lib/Pluggable.pm6 (Pluggable) line 8
  in method test at t/01-tests.t line 17
  in block <unit> at t/01-tests.t line 70
```

#### Image::RGBA::Text
- [Log](https://gist.github.com/samcv/9a9e43ff33bd053be372175600977b97)
- [X] Reported https://github.com/cygx/p6-image-rgba-text/pull/2
- [ ] Fixed

#### Facter:ver('0.04'):auth('Cosimo Streppone')
- [Log](https://travis-ci.org/samcv/rakudo-appimage/jobs/223092220#L4171)
- [ ] Reported
- [ ] Fixed

#### App::jsonv:ver('0.01'):auth('David Farrell Dmitry Yaskolko')
- [Log](https://travis-ci.org/samcv/rakudo-appimage/jobs/223092221#L3888)
- [ ] Reported
- [ ] Fixed

####  BioInfo:ver('0.4.3'):auth('Matt Oates')
- [Log](https://travis-ci.org/samcv/rakudo-appimage/jobs/223092218#L2116)
- [ ] Reported
- [ ] Fixed

#### Math::ContinuedFractions
- [Log](https://travis-ci.org/samcv/rakudo-appimage/jobs/223092218#L1528)
- [ ] Reported
- [ ] Fixed

#### Perl6-Math-Quaternion:auth('Bruce Gray')
- [Log](https://travis-ci.org/samcv/rakudo-appimage/jobs/223092221#L3814)
- [ ] Reported
- [ ] Fixed

#### Math::PascalTriangle:ver('0.1.0')
- [Log](https://travis-ci.org/samcv/rakudo-appimage/jobs/223092218#L2343)
- [ ] Reported
- [ ] Fixed

#### Flower
- [Log](https://travis-ci.org/samcv/rakudo-appimage/jobs/223092221#L3555)
- [ ] Reported
- [ ] Fixed

#### Hinges
- [Log](https://travis-ci.org/samcv/rakudo-appimage/jobs/223092221#L3670)
- [ ] Reported
- [ ] Fixed

#### Druid
- [Log](https://travis-ci.org/samcv/rakudo-appimage/jobs/223092221#L3959)
- [X] Reported https://github.com/masak/druid/issues/8
- [x] Fixed

#### GGE
- [Log](https://travis-ci.org/samcv/rakudo-appimage/jobs/223092220#L4035)
- [ ] Reported
- [ ] Fixed

#### Term::ANSIColor
- [Log](https://travis-ci.org/samcv/rakudo-appimage/jobs/223092218#L1667)
- [ ] Reported
- [ ] Fixed
This module module is deprecated. It is unlikely that we need to fix it. Perhaps remove?

#### Pod::PerlTricks
- [ ] Reported
- [ ] Fixed

#### Template::Anti
- [ ] Reported
- [ ] Fixed

#### Class::Utils
- [x] Reported https://github.com/sirrobert/Class-Utils/issues/5
- [ ] Fixed

#### Sum
- [ ] Reported
- [ ] Fixed

#### XML::Parser::Tiny
- [ ] Reported
- [ ] Fixed

#### Kains
- [ ] Reported
- [ ] Fixed

#### File::Find::Duplicates
- [ ] Reported
- [ ] Fixed

#### Test::Junkie
- [ ] Reported
- [ ] Fixed

#### [Acme::DSON](https://github.com/xfix/Acme-DSON)
- [ ] Reported
- [ ] Fixed

#### [Acme::Flutterby](https://github.com/byterock/Acme-Flutterby)
- [ ] Reported
- [ ] Fixed

#### [Acme::Sudoku](https://github.com/pierre-vigier/Perl6-Acme-Sudoku)
- [ ] Reported
- [ ] Fixed

#### [Adventure::Engine](https://github.com/masak/Adventure-Engine)
- [ ] Reported
- [ ] Fixed

#### [Algorithm::Kruskal](https://github.com/titsuki/p6-Algorithm-Kruskal)
- [ ] Reported
- [x] Fixed

#### [Algorithm::LibSVM](https://github.com/titsuki/p6-Algorithm-LibSVM)
- [ ] Reported
- [x] Fixed

#### [Algorithm::Viterbi](https://github.com/arnsholt/Algorithm-Viterbi)
- [ ] Reported
- [ ] Fixed

#### [App::P6Dx](https://github.com/MadcapJake/p6dx)
- [ ] Reported
- [ ] Fixed

#### [AttrX::InitArg](https://github.com/LLFourn/p6-AttrX-InitArg)
- [ ] Reported
- [ ] Fixed

#### [Audio::OggVorbis](https://github.com/Xliff/p6-audio-oggvorbis)
- [ ] Reported
- [ ] Fixed

#### [Audio::PortMIDI](https://github.com/Perl6-Noise-Gang/Audio-PortMIDI)
- [x] Reported
- [x] Fixed

#### [Audio::Silan](https://github.com/jonathanstowe/Audio-Silan)
- [x] Reported
- [x] Fixed

#### [Auth::SAML2](https://github.com/retupmoca/P6-SAML)
- [ ] Reported
- [ ] Fixed

#### [Binary::Structured](https://github.com/avuserow/perl6-binary-structured)
- [ ] Reported
- [ ] Fixed

#### [BioInfo](https://github.com/MattOates/BioInfo)
- [ ] Reported
- [ ] Fixed

#### [C::Parser](https://github.com/andydude/p6-c-parser)
- [ ] Reported
- [ ] Fixed

#### [CompUnit::DynamicLib](https://github.com/zostay/p6-CompUnit-DynamicLib)
- [ ] Reported
- [ ] Fixed

#### [Coroutines](https://github.com/tadzik/Coroutines)
- [ ] Reported
- [ ] Fixed

#### [Crust](https://github.com/tokuhirom/p6-Crust)
- [ ] Reported
- [ ] Fixed

#### [Crypt::TweetNacl](https://github.com/soundart/perl6-tweetnacl)
- [ ] Reported
- [ ] Fixed

#### [DBDish::ODBC](https://github.com/salortiz/DBDish-ODBC)
- [ ] Reported
- [ ] Fixed

#### [Data::Dump::Tree](https://github.com/nkh/P6-Data-Dump-Tree)
- [ ] Reported
- [ ] Fixed

#### [DateTime::DST](https://github.com/zostay/DateTime-DST)
- [ ] Reported
- [ ] Fixed

#### [Digest::xxHash](https://github.com/atweiden/digest-xxhash)
- [ ] Reported
- [ ] Fixed

#### [Email::Notmuch](https://github.com/goneri/p6-Email-Notmuch)
- [ ] Reported
- [ ] Fixed

#### [File::LibMagic](https://github.com/autarch/perl6-File-LibMagic)
- [ ] Reported
- [ ] Fixed

#### [GTK::Scintilla](https://github.com/azawawi/perl6-gtk-scintilla)
- [ ] Reported
- [ ] Fixed

#### [Geo::Region:auth('Nick Patch')](https://github.com/patch/geo-region-pm6)
- [ ] Reported
- [ ] Fixed

#### [GTK::Simple](https://github.com/perl6/gtk-simple)
- [ ] Reported
- [ ] Fixed

#### [GeoIP::City](https://github.com/bbkr/GeoIPerl6)
- [ ] Reported
- [ ] Fixed

#### [Grammar::Debugger](https://github.com/jnthn/grammar-debugger)
- [ ] Reported
- [ ] Fixed

#### [Gumbo:auth('Sylvain Colinet')](https://github.com/Skarsnik/perl6-gumbo)
- [ ] Reported
- [ ] Fixed

#### [HTML::MyHTML](https://github.com/MadcapJake/p6-MyHTML)
- [ ] Reported
- [ ] Fixed

#### [HTML::Restrict](https://github.com/stmuk/p6-html-restrict)
- [ ] Reported
- [ ] Fixed

#### [HTML::Tag](https://github.com/adaptiveoptics/HTML-Tag)
- [ ] Reported
- [ ] Fixed

#### [HTTP::Server::Async::Plugins::Router::Simple](https://github.com/tony-o/perl6-http-server-async-plugins-router-simple)
- [ ] Reported
- [ ] Fixed

#### [HTTP::Server::Logger](https://github.com/tony-o/perl6-http-server-logger)
- [ ] Reported
- [ ] Fixed

#### [HTTP::Server::Threaded](https://github.com/perl6/perl6-http-server-threaded)
- [ ] Reported
- [ ] Fixed

#### [HTTP::Server::Tiny](https://github.com/tokuhirom/p6-HTTP-Server-Tiny)
- [ ] Reported
- [ ] Fixed

#### [Hydrate:auth('vendethiel')](https://github.com/vendethiel/hydrate6)
- [ ] Reported
- [ ] Fixed

#### [IO::Path::More:auth('labster')](https://github.com/labster/p6-IO-Path-More)
- [ ] Reported
- [ ] Fixed

#### [IRC::Art](https://github.com/Skarsnik/perl6-irc-art)
- [ ] Reported
- [ ] Fixed

#### [Image::Resize](https://github.com/dagurval/perl6-image-resize)
- [ ] Reported
- [ ] Fixed

#### [Ini::Storage](https://github.com/jaffa4/inistorage)
- [ ] Reported
- [ ] Fixed

#### [Inline::Lua:auth('raydiak')](https://github.com/raydiak/Inline-Lua)
- [ ] Reported
- [ ] Fixed

#### [IoC](https://github.com/jasonmay/perl6-ioc)
- [ ] Reported
- [ ] Fixed

#### [JSON::Path](https://github.com/jnthn/json-path)
- [ ] Reported
- [ ] Fixed

#### [JavaScript::SpiderMonkey](https://github.com/hartenfels/Javascript-SpiderMonkey)
- [ ] Reported
- [ ] Fixed

#### [JsonC](https://github.com/salortiz/JsonC)
- [ ] Reported
- [ ] Fixed

#### [LMDB](https://github.com/salortiz/p6-LMDB)
- [ ] Reported
- [ ] Fixed

#### [LibZip](https://github.com/azawawi/perl6-libzip)
- [ ] Reported
- [ ] Fixed

#### [Lingua::Number:auth('github:labster')](https://github.com/labster/p6-Lingua-Number)
- [ ] Reported
- [ ] Fixed

#### [META6::bin](https://github.com/gfldex/perl6-meta6-bin)
- [ ] Reported
- [ ] Fixed

#### [MagickWand](https://github.com/azawawi/perl6-magickwand)
- [ ] Reported
- [ ] Fixed

#### [Manifesto](https://github.com/jonathanstowe/Manifesto)
- [x] Reported
- [ ] Fixed

#### [Marpa](https://github.com/drforr/perl6-Marpa)
- [ ] Reported
- [ ] Fixed

#### [Masquerade:auth('Sir Robert Burbridge')](https://github.com/sirrobert/Masquerade)
- [ ] Reported
- [ ] Fixed

#### [Math::Sequences](https://github.com/ajs/perl6-Math-Sequences)
- [ ] Reported
- [ ] Fixed

#### [Math::Symbolic:auth('raydiak')](https://github.com/raydiak/Math-Symbolic)
- [ ] Reported
- [ ] Fixed

#### [Modular](https://github.com/grondilu/p6-modular)
- [ ] Reported
- [ ] Fixed

#### [Module::Does](https://github.com/tony-o/perl6-module-does)
- [ ] Reported
- [ ] Fixed

#### [MongoDB](https://github.com/MARTIMM/mongo-perl6-driver)
- [ ] Reported
- [ ] Fixed

#### [NASA](https://github.com/zoffixznet/perl6-NASA)
- [ ] Reported
- [ ] Fixed

#### [Net::AMQP](https://github.com/retupmoca/P6-Net-AMQP)
- [x] Reported
- [x] Fixed

#### [Net::Packet](https://github.com/jpve/perl6-net-packet)
- [ ] Reported
- [ ] Fixed

#### [Net::Pcap](https://github.com/jpve/perl6-net-pcap)
- [ ] Reported
- [ ] Fixed

#### [Net::ZMQ:auth('Arne Skjærholt')](https://github.com/arnsholt/Net-ZMQ)
- [ ] Reported
- [ ] Fixed

#### [November:auth('github:viklund')](https://github.com/viklund/november)
- [ ] Reported
- [ ] Fixed

#### [Path::Map](https://github.com/fjwhittle/p6-Path-Map)
- [ ] Reported
- [ ] Fixed

#### [Perl6 Snowball Binding](https://github.com/Sufrostico/perl6-snowball)
- [ ] Reported
- [ ] Fixed

#### [Plosurin](https://github.com/zag/plosurin)
- [ ] Reported
- [ ] Fixed

#### [Pod::Coverage](https://github.com/teodozjan/pod6-coverage)
- [ ] Reported
- [ ] Fixed

#### [Pod::TreeWalker](https://github.com/autarch/perl6-Pod-TreeWalker)
- [ ] Reported
- [ ] Fixed

#### [Proc::Screen](https://github.com/skids/perl6-Proc-Screen)
- [ ] Reported
- [ ] Fixed

#### [RPi::GpioDirect](https://github.com/donaldh/Perl6-RPi-GpioDirect)
- [ ] Reported
- [ ] Fixed

#### [Rakudo::Perl6::Parsing](https://github.com/jaffa4/perl6parsing)
- [ ] Reported
- [ ] Fixed

#### [Redis](https://github.com/cofyc/perl6-redis)
- [ ] Reported
- [ ] Fixed

#### [SDL](https://github.com/PerlGameDev/SDL6)
- [ ] Reported
- [ ] Fixed

#### [Search::Dict](https://github.com/zengargoyle/p6-Search-Dict)
- [ ] Reported
- [ ] Fixed

#### [Slang::Roman](https://github.com/drforr/perl6-slang-roman)
- [ ] Reported
- [ ] Fixed

#### [Slang::SQL](https://github.com/tony-o/perl6-slang-sql)
- [ ] Reported
- [ ] Fixed

#### [Sprockets:auth('github:vendethiel')](https://github.com/vendethiel/Sprockets.pl)
- [ ] Reported
- [ ] Fixed

#### [String::CamelCase](https://github.com/yowcow/p6-String-CamelCase)
- [ ] Reported
- [ ] Fixed

#### [Template::Mustache:auth('github:softmoth')](https://github.com/softmoth/p6-Template-Mustache)
- [ ] Reported
- [ ] Fixed

#### [Template::Protone](https://github.com/tony-o/perl6-template-protone)
- [ ] Reported
- [ ] Fixed

#### [Test::Deeply::Relaxed](https://github.com/ppentchev/perl6-Test-Deeply-Relaxed)
- [ ] Reported
- [ ] Fixed

#### [Test::Lab](https://github.com/MadcapJake/Test-Lab)
- [ ] Reported
- [ ] Fixed

#### [Text::Abbrev](https://github.com/xfix/perl6-Text-Abbrev)
- [ ] Reported
- [ ] Fixed

#### [Text::Fortune](https://github.com/zengargoyle/Text-Fortune)
- [ ] Reported
- [ ] Fixed

#### [Text::Indented](https://github.com/masak/text-indented)
- [ ] Reported
- [ ] Fixed

#### [Text::LTSV](https://github.com/moznion/p6-Text-LTSV)
- [ ] Reported
- [ ] Fixed

#### [Text::Markdown::Discount](https://github.com/hartenfels/Text-Markdown-Discount)
- [ ] Reported
- [ ] Fixed

#### [Text::T9](https://github.com/tadzik/Text-T9)
- [ ] Reported
- [ ] Fixed

#### [Time::Duration](https://github.com/dagurval/p6-Time-Duration)
- [ ] Reported
- [ ] Fixed

#### [TinyCC](https://github.com/cygx/p6-tinycc)
- [ ] Reported
- [ ] Fixed

#### [Typed::Subroutines](https://github.com/tadzik/Typed-Subroutines)
- [ ] Reported
- [ ] Fixed

#### [Web::Scraper](https://github.com/tony-o/perl6-web-scraper)
- [ ] Reported
- [ ] Fixed

#### [WebService::Justcoin](https://github.com/dagurval/p6-webservice-justcoin)
- [ ] Reported
- [ ] Fixed

#### [flow](https://github.com/tony-o/perl6-flow)
- [ ] Reported
- [ ] Fixed

#### [overload::constant](https://github.com/FROGGS/p6-overload-constant)
- [ ] Reported
- [ ] Fixed

# ???
- Panda::Builder

# Warnings
#### MPD
- https://github.com/tadzik/perl6-MPD/issues/6

#### FastCGI:ver('0.9.0')
```
Potential difficulties:
    Useless use of hash composer on right side of hash assignment; did you mean := instead?
    at /home/samcv/a/zef/site#sources/D33B2CF81EB010BB6A219D2AF5F873163A6DBF44 (FastCGI::Protocol):143
```

**Comment by zoffixznet** [comment] 2017-04-26 18:19
>  sena_kun buggable, eco Tardis
>    sena_kun, Nothing found
> Is it even here? I cannot find it, though I remember such a module.

Tardis was removed from ecosystem: https://github.com/perl6/ecosystem/commit/74a4b9dd5f5d929d70245e3f2be7b5d8ee394d0a

**Comment by teodozjan** [comment] 2017-04-26 18:57
Pod::Coverage is failing because rakudo has changed and I don't know gow to align it to new behaviour

**Comment by zoffixznet** [comment] 2017-04-26 19:32
> Pod::Coverage is failing because rakudo has changed and I don't know gow to align it to new behaviour

Sent a small PR fixing one problem. This diff fixes half of the other problems, and currently I'm at "crashes in `Pod::Coverage::Full.check`'s `require` because lib is not set" stage. Somewhere there it's missing `use lib <lib>` or `-Ilib`. Maybe you'd know where, since you know codebase better.

```diff
zoffix@leliana:/tmp/tmp.uDxsRRfX5p$ gd
diff --git a/lib/Pod/Coverage/Anypod.pm6 b/lib/Pod/Coverage/Anypod.pm6
index 47724ce..d4687b8 100644
--- a/lib/Pod/Coverage/Anypod.pm6
+++ b/lib/Pod/Coverage/Anypod.pm6
@@ -25,7 +25,7 @@ method !file-haspod {
 
 sub has-pod($path) returns Bool {
     #dd qqx/$*EXECUTABLE-NAME --doc $path/.lines.elems;
-    $path.IO ~~ :f and qqx/$*EXECUTABLE-NAME --doc $path/.lines.elems.Bool;
+    $path.IO ~~ :f and qqx/$*EXECUTABLE-NAME --Ilib --doc $path/.lines.elems.Bool;
 }
 
 
diff --git a/lib/Pod/Coverage/Full.pm6 b/lib/Pod/Coverage/Full.pm6
index 45f4bcf..bf3e87e 100644
--- a/lib/Pod/Coverage/Full.pm6
+++ b/lib/Pod/Coverage/Full.pm6
@@ -137,9 +137,9 @@ method correct-pod($filename) {
 }
 
 sub read_pod($filename){
-    say "$*EXECUTABLE-NAME --doc=Keywords $filename";
-    dd qqx/$*EXECUTABLE-NAME --doc=Keywords $filename/;
-    return qqx/$*EXECUTABLE-NAME --doc=Keywords $filename/.lines;
+ #   say "$*EXECUTABLE-NAME --doc=Keywords $filename";
+#    dd qqx/$*EXECUTABLE-NAME --doc=Keywords $filename/;
+    return qqx/$*EXECUTABLE-NAME --Ilib --doc=Keywords $filename/.lines;
 }
 
 sub routine-result($what){
diff --git a/t/selftest.t b/t/selftest.t
index cb67ab4..18d3a53 100644
--- a/t/selftest.t
+++ b/t/selftest.t
@@ -5,5 +5,5 @@ use Test::Coverage;
 plan 3;
 
 ok 1, "At least loads";
-subtest_anypod_ok('META.info');
-subtest_coverage_ok('META.info');
+subtest_anypod_ok('META6.json');
+subtest_coverage_ok('META6.json');
zoffix@leliana:/tmp/tmp.uDxsRRfX5p$ 

```

**Comment by Altai-man** [comment] 2017-04-27 10:21
I have removed some modules out:
- DateTime::Math - fixed.
- DateTime::Utils - is not broken.
- if - fixed.
- Tardis - was removed.
- File::Ignore - was fixed.
- Druid - was fixed.
- Devel::Trace - was removed.

**Comment by samcv** [comment] 2017-04-27 19:17
Sent an email to @ingydotnet regarding [XXX](https://github.com/ingydotnet/xxx-pm6) and the lack of having a license field causing problems due to not being able to be worked on further without them. Will let you know if I hear back.

**Comment by pierre-vigier** [comment] 2017-04-28 02:35
I Fixed my module Math::Matrix, a change in behaviour of Seq/List broke it. It's fixed now.
I added the license in the META file as well

**Comment by zoffixznet** [comment] 2017-06-10 02:02
FWIW, I've built ecosystem toaster we'll be using to test for any regression in pre-release commits. https://toast.perl6.party/ (still need to add a way to view STDERR/OUT of install runs; though data is already in the SQLite DB you can download).

Could be used to see which modules fail.

**Comment by jonathanstowe** [comment] 2017-06-10 07:30
* Manifesto I know about - there is one test that is flaky on some platforms which I can't replicate locally so am struggling to fix.  May just TODO the test for the time being.
* Audio::Silan - it probably isn't checking the external dependency properly, just making a clean environment to see about that
* Audio::PortMIDI - I think this is probably a permissions problem I have seen on Linux machines which have never run any audio software before, it may be just check upfront and skip all the tests with a loud warning in this case.
* Net::AMQP - could be one of a number things as I haven't been testing it very frequently, but will look into it.

BTW I am smoke testing all of my modules for every rakudo change locally and Manifesto is the only one that I ever see any fails.

**Comment by titsuki** [comment] 2017-06-10 07:47
I have already fixed these:
+ Algorithm::Kruskal
+ Algorithm::LibSVM

**Comment by JJ** [comment] 2018-07-28 16:57
Could we use this for the bitrot squashathon?

**Comment by zoffixznet** [comment] 2018-07-28 17:45
We have the recent data on failing modules in toaster; I see no reason to use statics that are more than a year out of date. This issue should probably be closed.

**Comment by cosimo** [comment] 2018-07-28 18:35
Please ignore Facter, it was just an experiment, not worth including it.
String::CRC32 seems fine to me, plus the "log" entry points to an invalid link?

**Comment by zoffixznet** [comment] 2018-07-28 18:51
> String::CRC32 seems fine to me, plus the "log" entry points to an invalid link

Right. This Issue is way too out of date. Closing.

**Closed by zoffixznet** 2018-07-28 18:51 UTC

**Comment by bbkr** [comment] 2018-07-30 07:51
GeoIP::City is deprecated, new module is https://github.com/bbkr/GeoIP2.

The reason is that GeoIP::City supports old binary database formats that will be phased out in early 2019, but they are already not accessible for download from Maxmind site. And that's why tests fail.

I want to keep this module in ecosystem till phase out so I'll try to fix tests to use fixed database versions. Thanks for pointing this out.

**Comment by AlexDaniel** [comment] 2018-08-05 16:32
> Right. This Issue is way too out of date. Closing.

FWIW See https://github.com/perl6/ecosystem-unbitrot a slightly newer attempt to fix the ecosystem.
